### ISSUE TITLE
Potential use case

### ISSUE THREAD

**Issue by ismailmayat** [SDKits/ExamineX#2]
Shannon,
So we currently have a site in azure the examine setup is as follows:

- Examine umbraco content
- PDF content - PDF indexer but the pdf engine swapper out with apache tika
- Custom index of external xml feed
- Multi index searcher that searches over the above 3
- Faceting using simplefaceted contrib package

We have 2 webapps using same db. One app is backoffice only and the other is the frontend.

We currently have 2 issues one is when we deploy on azure via a slot sometimes the custom index fails due to lock. We have to manually delete the lock and search then works again. That custom index is rebuilt on a daily basis at 1am using azure function.

We are also starting to see issue where sometimes for no reason the custom index locks and we have to delete the file again. Hence we wanted new solution where indexes are in the cloud so this looks like a good fit.  Looking at my setup I guess I will need to do some rewrite with faceting do you think everything else will work as is or will I need to re write more stuff. I suspect PDF indexing may need some re work?

Thanks

Ismail

**Comment by Shazwazza** [comment]
Hi! 

Regarding index locks i'm unsure if you mean the files are locked or you actually have a lucene lock error? (they are different) In Umbraco Examine we use a custom Lucene lock that doesn't use the native file system lock since this always causes issues with Azure and other web hosts. We use a simple file lock so that the lock file isn't actually locked at the OS level since Umbraco controls access to the indexes with MainDom - this is probably part of the issue you are hitting because there has been issues with MainDom in v8 which is why we made the SqlMainDomLock setting but that has issues until 8.6.2 since it didn't work with Load Balancing and Slot Swapping is still Load Balancing in a way. 

But regarding ExamineX - working around limitations of local/temp Lucene files in Azure has always been a bit of a pain point which is why this has been made. There's a lot of work arounds in play to make Lucene behave with Azure as you know, from the local/temp synced files from main storage to different configurations for load balancing and the need to rebuild indexes locally for front-end scaling. None of that is ideal.

ExamineX will deal with your Umbraco indexes without any real code changes. ExamineX has a Nuget package to deal with the Umbraco PDF Indexer so if you are just extending that one, then this should work for that too without any code changes. It's easy to create custom indexes in ExamineX, its very similar to Examine but instead of creating or inheriting from a `LuceneIndex` you use an `AzureSearchIndex`. The rest of any Examine APIs you currently use don't need to be changed at all. 

Faceting is fully supported in azure search and is probably much easier and more powerful to implement than with Lucene. 

The tricky one is multi-index searching since this isn't built into azure search yet, there's an open ticket for that here https://feedback.azure.com/forums/263029-azure-search/suggestions/16700506-search-multiple-indexes-at-once. I wonder if there's a work around to consider for that though. Maybe you don't need multiple indexes and instead you just have a single index? this is sort of what the index type and index category are for and since an ID is a string if you're worried about overlapping INT ids you could always prefix them with the type.

**Comment by Shazwazza** [comment]
Closing this ticket but just let me know if you need more info.
