### ISSUE TITLE
Indexers are disabled

### ISSUE THREAD

**Issue by skartknet** [SDKits/ExamineX#69]
Examine Version: 4.0.0-beta 1
Umbraco Version: 10.0.0.1

Indexers are created in a 'disabled' state. If try to run them manually from the Azure Search dashboard I get the following error:

`Data source does not contain column '__NodeId', which is required because it maps to the document key field 'x__NodeId' in the index 'test-external'. Ensure that the '__NodeId' column is present in the data source, or add a field mapping that maps one of the existing column names to 'x__NodeId'.`

**Comment by Shazwazza** [comment]
This is the same issue as here https://github.com/SDKits/ExamineX/issues/68#issuecomment-1222930192

They are first created in a disabled state and then on a background thread they are enabled and run, this is to avoid any errors (such as this one) when saving media. Typically they will be enabled in a very short amount of time but due to some of your blob files not containing the __NodeId metadata, this exception will be thrown.
