### ISSUE TITLE
String properties being stored as StringCollection

### ISSUE THREAD

**Issue by shgreig-mtm** [SDKits/ExamineX#74]
![image](https://user-images.githubusercontent.com/54805128/201068076-2c56a6df-d991-419c-abaf-243bef0efc13.png)
String properties that are shared across multiple pages are being created in the index as a StringCollection rather than a string.

We are querying the Azure index directly so this is causing us issues

We are on Umbraco 10 and ExamineX beta 4 2

**Comment by Shazwazza** [comment]
Hi, StringCollection is the default storage mechanism so that it is possible to index multiple values per field - to be in line with how Lucene works by default. If you want to change the storage type for a field, you can change the field type for a given field. The docs are here https://examinex.online/customization#default-field-types--analyzers
