### ISSUE TITLE
Not able to search content for media items.

### ISSUE THREAD

**Issue by jt3432** [SDKits/ExamineX#83]
I am hoping this is a stupid question and I just missed something. I am having an issue searching media content. This seemed to work before but has now stopped. We are using blob storage, have all the Nuget packages per the ExamineX documentation installed, don't have any doc's or media properties named "content", but the contents of PDF's and other files are not being added to the external or internal indexes. Directly searching Azure Cognitive Search via the API shows the content field is included but null and it is completely missing on the Umbraco side (I imagine that is because it is null/empty in the index). Is there a configuration setting that needs to be set now to make content of files get indexes to the content field? Thanks.

**Comment by Shazwazza** [comment]
Hi, as we've resolved this in another thread I will close the issue. 

For others: the underlying issue is that there was existing media prior to installing the ExamineX blob media package. This meant that all blob items didn't have the required metadata for Azure Search to index the media items. A re-save of all media items was required in this case to add the correct metadata. 

In the future, a health check will be added whereby we can auto resolve this issue and add all metadata to all required blob media items.
